# Generated by Django 5.0.6 on 2024-05-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='date_joined',
            field=models.DateTimeField(default='2024-05-30 10:44:32.589112'),
        ),
    ]
