# Generated by Django 5.0.6 on 2024-05-30 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userregistration_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='date_joined',
            field=models.DateTimeField(default='2024-05-30 10:47:24.539882'),
        ),
    ]
